[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
requests = "^2.32.3"
slack-bolt = "^1.21.3"
slack-sdk = "^3.33.5"
selenium = "^4.27.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
